coverage:
  range: 50...100
  precision: 2
  round: down
  status:
    default:
      threshold: 5%
    unit:
      flags: unit
    integration:
      flags: integration
    end_to_end:
      flags: end_to_end

flags:
  unit:
    paths:
      - .
  integration:
    paths:
      - .
  end_to_end:
    paths:
      - .

ignore:
  - ".tox/**/*"
  - "setup.py"
