coverage:
  precision: 2
  round: down
  range: 80...100
  status:
    unit:
      flags:
        - unit
    # integration:
    #   flags:
    #     - integration
    end_to_end:
      flags:
        - end_to_end

ignore:
  - ".tox/**/*"
  - "setup.py"
