coverage:
  range: 50...100
  precision: 2
  round: down
  status:
    project:
      unit:
        flags: unit
      integration:
        flags: integration
      end_to_end:
        flags: end_to_end

ignore:
  - ".tox/**/*"
  - "setup.py"
